# Generated by Django 3.1.7 on 2021-04-07 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='quiz.sample2')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_one', models.CharField(max_length=200)),
                ('ex_two', models.CharField(max_length=200)),
                ('ex_three', models.CharField(max_length=200)),
                ('ex_four', models.CharField(max_length=200)),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex', to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_one', models.CharField(max_length=200)),
                ('comm_two', models.CharField(max_length=200)),
                ('comm_three', models.CharField(max_length=200)),
                ('comm_four', models.CharField(max_length=200)),
                ('comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm', to='quiz.quiz')),
            ],
        ),
    ]
